using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Drawing;
using System.Globalization;
using System.IO;
using System.IO.Compression;
using System.Linq;
using System.Windows.Forms;
using System.Xml.Linq;
using System.Xml.Serialization;

namespace ScadentarTransportatori {
[Serializable] public class Invoice {
 public int Year; public int NrCrt; public string Transportator=""; public string Comanda=""; public string Factura=""; public decimal TotalLei; public decimal TotalEur; public string Iban=""; public DateTime DataPrimire=DateTime.Today; public int ZileScadenta=30; public DateTime Scadenta=DateTime.Today.AddDays(30); public string ScadentaText=""; public bool ScadentaInvalida=false; public DateTime? DataPlatii; public string Observatii="";
 public bool Platita { get { return DataPlatii.HasValue; } }
}
[Serializable] public class AppData { public List<int> Years=new List<int>(); public List<Invoice> Invoices=new List<Invoice>(); }

public class MainForm:Form {
 AppData data; string baseDir, dbFile, backupDir; ComboBox yearBox, transportBox; TextBox transportSearch; DataGridView grid; Label lblDue,lblTotal,lblTotalEur,lblDueEur,lblOld,lblCount; BindingList<Invoice> view=new BindingList<Invoice>(); bool refreshingYear=false, refreshingTransport=false, onlyDue=false; Button btnDue;
 public MainForm(){ Text="OTL - Scadentar Facturi Transportatori v2.4"; Width=1540; Height=900; MinimumSize=new Size(1200,700); BackColor=Color.FromArgb(236,242,247); StartPosition=FormStartPosition.CenterScreen; Font=new Font("Segoe UI",9F); baseDir=Path.Combine(Environment.GetFolderPath(Environment.SpecialFolder.MyDocuments),"ScadentarTransportatori"); dbFile=Path.Combine(baseDir,"scadentar.xml"); backupDir=Path.Combine(baseDir,"Backup"); Directory.CreateDirectory(baseDir); Directory.CreateDirectory(backupDir); LoadData(); BuildUi(); RefreshAll(); AutoBackup(); }
 void BuildUi(){
  var root=new TableLayoutPanel{Dock=DockStyle.Fill,ColumnCount=1,RowCount=4,Padding=new Padding(0),BackColor=Color.FromArgb(236,242,247)};
  root.RowStyles.Add(new RowStyle(SizeType.Absolute,104)); root.RowStyles.Add(new RowStyle(SizeType.Absolute,86)); root.RowStyles.Add(new RowStyle(SizeType.Absolute,54)); root.RowStyles.Add(new RowStyle(SizeType.Percent,100)); Controls.Add(root);

  var header=new Panel{Dock=DockStyle.Fill,BackColor=Color.FromArgb(5,31,52),Padding=new Padding(22,10,22,8)}; root.Controls.Add(header,0,0);
  var logo=new Label{Text="OTL",ForeColor=Color.White,Font=new Font("Segoe UI",31F,FontStyle.Bold|FontStyle.Italic),AutoSize=true,Left=24,Top=12}; header.Controls.Add(logo);
  var company=new Label{Text="OCTAV TRANSPORT LOGISTIC",ForeColor=Color.FromArgb(190,210,225),Font=new Font("Segoe UI",9F,FontStyle.Bold),AutoSize=true,Left=28,Top=67}; header.Controls.Add(company);
  var sep=new Panel{BackColor=Color.FromArgb(25,108,166),Left=210,Top=16,Width=2,Height=68}; header.Controls.Add(sep);
  var title=new Label{Text="SCADENTAR FACTURI TRANSPORTATORI",ForeColor=Color.White,Font=new Font("Segoe UI",21F,FontStyle.Bold),AutoSize=true,Left=232,Top=16}; header.Controls.Add(title);
  var sub=new Label{Text="Control plati  |  Scadente  |  Transportatori",ForeColor=Color.FromArgb(164,196,218),Font=new Font("Segoe UI",10F),AutoSize=true,Left=235,Top=59}; header.Controls.Add(sub);
  var badge=new Label{Text="TRANSPORT  •  LOGISTICA  •  PARTENERIAT",ForeColor=Color.White,BackColor=Color.FromArgb(13,83,130),Font=new Font("Segoe UI",9F,FontStyle.Bold),AutoSize=true,Padding=new Padding(12,7,12,7),Anchor=AnchorStyles.Top|AnchorStyles.Right}; badge.Left=Width-390;badge.Top=28;header.Controls.Add(badge);header.Resize+=(s,e)=>badge.Left=header.ClientSize.Width-badge.Width-24;

  var stats=new FlowLayoutPanel{Dock=DockStyle.Fill,Padding=new Padding(12,9,8,7),WrapContents=false,AutoScroll=true,BackColor=Color.FromArgb(222,232,240)};
  lblTotal=Stat(stats,"TOTAL DE PLATA LEI"); lblTotalEur=Stat(stats,"TOTAL DE PLATA EUR"); lblDue=Stat(stats,"TOTAL SCADENT LEI"); lblDueEur=Stat(stats,"TOTAL SCADENT EUR"); lblCount=Stat(stats,"FACTURI NEPLATITE"); lblOld=Stat(stats,"RESTANTE ANI ANTERIORI"); root.Controls.Add(stats,0,1);

  var top=new FlowLayoutPanel{Dock=DockStyle.Fill,Padding=new Padding(12,10,8,7),WrapContents=false,AutoScroll=true,BackColor=Color.White};
  top.Controls.Add(new Label{Text="AN",ForeColor=Color.FromArgb(45,62,75),Font=new Font("Segoe UI",9F,FontStyle.Bold),AutoSize=true,Padding=new Padding(0,7,2,0)}); yearBox=new ComboBox{DropDownStyle=ComboBoxStyle.DropDownList,Width=84,Height=30}; yearBox.SelectedIndexChanged+=(s,e)=>{if(!refreshingYear)RefreshAll();}; top.Controls.Add(yearBox);
  top.Controls.Add(new Label{Text="TRANSPORTATOR",ForeColor=Color.FromArgb(45,62,75),Font=new Font("Segoe UI",9F,FontStyle.Bold),AutoSize=true,Padding=new Padding(12,7,2,0)}); transportBox=new ComboBox{DropDownStyle=ComboBoxStyle.DropDownList,Width=205,Height=30}; transportBox.SelectedIndexChanged+=(s,e)=>{if(!refreshingTransport)RefreshViewAndTotals();}; top.Controls.Add(transportBox);
  transportSearch=new TextBox{Width=165,Height=30,Margin=new Padding(4,2,8,0)}; transportSearch.TextChanged+=(s,e)=>RefreshViewAndTotals(); top.Controls.Add(transportSearch);
  AddButton(top,"+ AN",(s,e)=>AddYear()); AddButton(top,"+ FACTURA NOUA",(s,e)=>EditInvoice(null)); btnDue=AddButton(top,"DOAR SCADENTE",(s,e)=>ToggleDue()); AddButton(top,"MARCAJ PLATITA",(s,e)=>MarkPaid()); AddButton(top,"IMPORT EXCEL",(s,e)=>ImportExcel()); AddButton(top,"EXPORT CSV",(s,e)=>ExportCsv()); AddButton(top,"BACKUP",(s,e)=>{Backup(); MessageBox.Show("Backup creat.");}); AddButton(top,"RESTAUREAZA",(s,e)=>Restore()); root.Controls.Add(top,0,2);

  var gridHost=new Panel{Dock=DockStyle.Fill,Padding=new Padding(12,8,12,12),BackColor=Color.FromArgb(236,242,247)}; root.Controls.Add(gridHost,0,3);
  grid=new DataGridView{Dock=DockStyle.Fill,AutoGenerateColumns=false,ReadOnly=true,AllowUserToAddRows=false,SelectionMode=DataGridViewSelectionMode.FullRowSelect,MultiSelect=false,RowHeadersVisible=false,AutoSizeColumnsMode=DataGridViewAutoSizeColumnsMode.Fill,ColumnHeadersVisible=true,ColumnHeadersHeight=40,ColumnHeadersHeightSizeMode=DataGridViewColumnHeadersHeightSizeMode.DisableResizing,EnableHeadersVisualStyles=false,BackgroundColor=Color.White,BorderStyle=BorderStyle.None,GridColor=Color.FromArgb(215,224,231),RowTemplate={Height=30}};
  grid.ColumnHeadersDefaultCellStyle.Font=new Font("Segoe UI",9F,FontStyle.Bold); grid.ColumnHeadersDefaultCellStyle.Alignment=DataGridViewContentAlignment.MiddleCenter; grid.ColumnHeadersDefaultCellStyle.BackColor=Color.FromArgb(8,62,99); grid.ColumnHeadersDefaultCellStyle.ForeColor=Color.White; grid.DefaultCellStyle.SelectionBackColor=Color.FromArgb(194,221,239);grid.DefaultCellStyle.SelectionForeColor=Color.Black;grid.AlternatingRowsDefaultCellStyle.BackColor=Color.FromArgb(246,249,251); gridHost.Controls.Add(grid);
  string[] heads={"NR. CRT.","TRANSPORTATOR","COMANDA","FACTURA / DATA","TOTAL LEI","TOTAL EUR","IBAN","DATA PRIMIRE","SCADENTA","ZILE INTARZIERE","DATA PLATII","OBSERVATII"}; string[] props={"NrCrt","Transportator","Comanda","Factura","TotalLei","TotalEur","Iban","DataPrimire","Scadenta","Delay","DataPlatii","Observatii"};
  for(int i=0;i<heads.Length;i++){ var c=new DataGridViewTextBoxColumn{HeaderText=heads[i],Name=props[i],SortMode=DataGridViewColumnSortMode.NotSortable}; grid.Columns.Add(c); } grid.Columns[0].FillWeight=42; grid.Columns[1].FillWeight=115; grid.Columns[6].FillWeight=120;
  grid.CellDoubleClick+=(s,e)=>{ if(e.RowIndex>=0) EditInvoice(view[e.RowIndex]);}; grid.CellFormatting+=FormatCell;
 }
 Button AddButton(Control p,string t,EventHandler h){var b=new Button{Text=t,AutoSize=true,Height=30,FlatStyle=FlatStyle.Flat,BackColor=Color.FromArgb(12,102,157),ForeColor=Color.White,Font=new Font("Segoe UI",8.5F,FontStyle.Bold),Margin=new Padding(4,0,4,0),Padding=new Padding(8,0,8,0),Cursor=Cursors.Hand};b.FlatAppearance.BorderSize=0;b.Click+=h;p.Controls.Add(b);return b;} Label Stat(Control p,string title){bool warn=title.Contains("SCADENT")||title.Contains("NEPLATITE");var l=new Label{Text=title+"\n0",Width=225,Height=61,BackColor=warn?Color.FromArgb(196,52,69):Color.FromArgb(8,82,128),ForeColor=Color.White,TextAlign=ContentAlignment.MiddleCenter,Font=new Font("Segoe UI",10F,FontStyle.Bold),Margin=new Padding(4),Padding=new Padding(4)};if(title.Contains("ANTERIORI"))l.BackColor=Color.FromArgb(76,98,113);p.Controls.Add(l);return l;}
 void LoadData(){ try{if(File.Exists(dbFile)){using(var f=File.OpenRead(dbFile)) data=(AppData)new XmlSerializer(typeof(AppData)).Deserialize(f);}else data=new AppData();}catch{data=new AppData();} if(data.Years.Count==0)data.Years.Add(DateTime.Today.Year);}
 void SaveData(){Directory.CreateDirectory(baseDir);using(var f=File.Create(dbFile))new XmlSerializer(typeof(AppData)).Serialize(f,data);}
 int CurrentYear(){int y;return int.TryParse(yearBox.SelectedItem==null?"":yearBox.SelectedItem.ToString(),out y)?y:DateTime.Today.Year;}
 void RefreshAll(){int sel=CurrentYear(); refreshingYear=true; try{ yearBox.Items.Clear(); foreach(var y in data.Years.Distinct().OrderByDescending(x=>x))yearBox.Items.Add(y.ToString()); var target=data.Years.Contains(sel)?sel:data.Years.Max(); yearBox.SelectedItem=target.ToString(); RefreshTransporters(target); RefreshViewAndTotals(); } finally { refreshingYear=false; }}
 void RefreshTransporters(int year){string prev=transportBox==null||transportBox.SelectedItem==null?"Toti transportatorii":transportBox.SelectedItem.ToString(); refreshingTransport=true; try{transportBox.Items.Clear();transportBox.Items.Add("Toti transportatorii");foreach(var t in data.Invoices.Where(x=>x.Year==year&&!string.IsNullOrWhiteSpace(x.Transportator)).Select(x=>x.Transportator.Trim()).Distinct(StringComparer.CurrentCultureIgnoreCase).OrderBy(x=>x))transportBox.Items.Add(t);int idx=transportBox.FindStringExact(prev);transportBox.SelectedIndex=idx>=0?idx:0;}finally{refreshingTransport=false;}}
 IEnumerable<Invoice> FilteredCurrentYear(){int y=CurrentYear();IEnumerable<Invoice> q=data.Invoices.Where(x=>x.Year==y);string tr=transportBox==null||transportBox.SelectedIndex<=0?"":transportBox.SelectedItem.ToString();if(!string.IsNullOrWhiteSpace(tr))q=q.Where(x=>string.Equals((x.Transportator??"").Trim(),tr.Trim(),StringComparison.CurrentCultureIgnoreCase));string search=transportSearch==null?"":transportSearch.Text.Trim();if(search.Length>0)q=q.Where(x=>(x.Transportator??"").IndexOf(search,StringComparison.CurrentCultureIgnoreCase)>=0);if(onlyDue)q=q.Where(x=>!x.Platita&&!x.ScadentaInvalida&&x.Scadenta.Date<=DateTime.Today.Date);return q;}
 void RefreshViewAndTotals(){if(grid==null||yearBox==null||yearBox.SelectedItem==null)return;var filtered=FilteredCurrentYear().ToList();view=new BindingList<Invoice>(filtered.OrderBy(x=>x.NrCrt<=0?int.MaxValue:x.NrCrt).ThenBy(x=>x.NrCrt).ToList());grid.Rows.Clear();foreach(var x in view){int delay=!x.Platita&&!x.ScadentaInvalida&&DateTime.Today.Date>x.Scadenta.Date?(DateTime.Today.Date-x.Scadenta.Date).Days:0;string scText=x.ScadentaInvalida?((string.IsNullOrWhiteSpace(x.ScadentaText)?"DATA INVALIDA":x.ScadentaText)+" - DATA INVALIDA"):(!string.IsNullOrWhiteSpace(x.ScadentaText)?x.ScadentaText:x.Scadenta.ToString("dd.MM.yyyy"));grid.Rows.Add(x.NrCrt,x.Transportator,x.Comanda,x.Factura,x.TotalLei.ToString("N2"),x.TotalEur.ToString("N2"),x.Iban,x.DataPrimire.ToString("dd.MM.yyyy"),scText,x.ScadentaInvalida?"-":delay.ToString(),x.DataPlatii.HasValue?x.DataPlatii.Value.ToString("dd.MM.yyyy"):"",x.Observatii);}var unpaid=filtered.Where(x=>!x.Platita).ToList();var due=unpaid.Where(x=>!x.ScadentaInvalida&&x.Scadenta.Date<=DateTime.Today.Date).ToList();int target=CurrentYear();var old=data.Invoices.Where(x=>x.Year<target&&!x.Platita&&!x.ScadentaInvalida&&x.Scadenta.Date<=DateTime.Today.Date);lblTotal.Text="TOTAL DE PLATA LEI\n"+unpaid.Sum(x=>x.TotalLei).ToString("N2")+" LEI";lblTotalEur.Text="TOTAL DE PLATA EUR\n"+unpaid.Sum(x=>x.TotalEur).ToString("N2")+" EUR";lblDue.Text="TOTAL SCADENT LEI\n"+due.Sum(x=>x.TotalLei).ToString("N2")+" LEI";lblDueEur.Text="TOTAL SCADENT EUR\n"+due.Sum(x=>x.TotalEur).ToString("N2")+" EUR";lblOld.Text="RESTANTE ANI ANTERIORI\n"+old.Sum(x=>x.TotalLei).ToString("N2")+" LEI / "+old.Sum(x=>x.TotalEur).ToString("N2")+" EUR";lblCount.Text="FACTURI NEPLATITE\n"+unpaid.Count;}

 void ToggleDue(){onlyDue=!onlyDue;if(btnDue!=null){btnDue.Text=onlyDue?"AFISEAZA TOATE":"DOAR SCADENTE";btnDue.BackColor=onlyDue?Color.FromArgb(196,52,69):Color.FromArgb(12,102,157);}RefreshViewAndTotals();}

 void FormatCell(object s,DataGridViewCellFormattingEventArgs e){if(e.RowIndex<0||e.RowIndex>=view.Count)return;var x=view[e.RowIndex]; if(x.Platita){grid.Rows[e.RowIndex].DefaultCellStyle.BackColor=Color.Honeydew;return;} if(x.ScadentaInvalida){grid.Rows[e.RowIndex].DefaultCellStyle.BackColor=Color.MistyRose;return;} int d=(DateTime.Today.Date-x.Scadenta.Date).Days; if(d>=1&&d<=10)grid.Rows[e.RowIndex].DefaultCellStyle.BackColor=Color.Khaki; else if(d>=11&&d<=20)grid.Rows[e.RowIndex].DefaultCellStyle.BackColor=Color.Orange; else if(d>20)grid.Rows[e.RowIndex].DefaultCellStyle.BackColor=Color.LightCoral;}
 void AddYear(){string v=Microsoft.VisualBasic.Interaction.InputBox("Introdu anul nou:","Adauga an",(data.Years.Max()+1).ToString());int y;if(int.TryParse(v,out y)&&y>=2000&&y<=2200&&!data.Years.Contains(y)){data.Years.Add(y);SaveData();RefreshAll();yearBox.SelectedItem=y.ToString();}}
 void EditInvoice(Invoice inv){var f=new InvoiceForm(inv,CurrentYear(), inv==null ? NextNrCrt(CurrentYear()) : inv.NrCrt);if(f.ShowDialog()==DialogResult.OK){if(inv==null)data.Invoices.Add(f.Result);else{int i=data.Invoices.IndexOf(inv);data.Invoices[i]=f.Result;} if(!data.Years.Contains(f.Result.Year))data.Years.Add(f.Result.Year);SaveData();RefreshAll();}}
 int NextNrCrt(int year){var nums=data.Invoices.Where(x=>x.Year==year&&x.NrCrt>0).Select(x=>x.NrCrt);return nums.Any()?nums.Max()+1:1;}
 void MarkPaid(){if(grid.SelectedRows.Count==0)return;int i=grid.SelectedRows[0].Index;if(i<0||i>=view.Count)return;var x=view[i];if(x.Platita){MessageBox.Show("Factura este deja marcata ca platita.");return;}using(var d=new DateDialog("Data platii",DateTime.Today)){if(d.ShowDialog()==DialogResult.OK){x.DataPlatii=d.Value;SaveData();RefreshAll();}}}
 void Backup(){if(!File.Exists(dbFile))SaveData();File.Copy(dbFile,Path.Combine(backupDir,"scadentar_"+DateTime.Now.ToString("yyyyMMdd_HHmmss")+".xml"),true);} void AutoBackup(){try{Backup();}catch{}}
 void Restore(){var o=new OpenFileDialog{InitialDirectory=backupDir,Filter="Backup XML|*.xml"};if(o.ShowDialog()!=DialogResult.OK)return;if(MessageBox.Show("Baza curenta va fi inlocuita. Continui?","Restaurare",MessageBoxButtons.YesNo)!=DialogResult.Yes)return;File.Copy(o.FileName,dbFile,true);LoadData();RefreshAll();}
 void ExportCsv(){var s=new SaveFileDialog{Filter="CSV|*.csv",FileName="Scadentar_"+CurrentYear()+".csv"};if(s.ShowDialog()!=DialogResult.OK)return;using(var w=new StreamWriter(s.FileName,false,System.Text.Encoding.UTF8)){w.WriteLine("NR. CRT.;Transportator;Comanda;Factura;Total LEI;Total EUR;IBAN;Data primire;Scadenta;Data platii;Observatii");foreach(var x in data.Invoices.Where(z=>z.Year==CurrentYear()))w.WriteLine(string.Join(";",new[]{x.NrCrt.ToString(),Q(x.Transportator),Q(x.Comanda),Q(x.Factura),x.TotalLei.ToString(CultureInfo.InvariantCulture),x.TotalEur.ToString(CultureInfo.InvariantCulture),Q(x.Iban),x.DataPrimire.ToString("dd.MM.yyyy"),Q(x.ScadentaInvalida?x.ScadentaText:(!string.IsNullOrWhiteSpace(x.ScadentaText)?x.ScadentaText:x.Scadenta.ToString("dd.MM.yyyy"))),x.DataPlatii.HasValue?x.DataPlatii.Value.ToString("dd.MM.yyyy"):"",Q(x.Observatii)}));}MessageBox.Show("Export finalizat.");}
 string Q(string s){return "\""+(s??"").Replace("\"","\"\"")+"\"";}
 void ImportExcel(){var o=new OpenFileDialog{Filter="Excel (*.xlsx)|*.xlsx"};if(o.ShowDialog()!=DialogResult.OK)return;try{var rows=XlsxReader.Read(o.FileName);int added=0,updated=0,repaired=0;foreach(var r in rows){if(string.IsNullOrWhiteSpace(r.Transportator)&&string.IsNullOrWhiteSpace(r.Factura))continue;Invoice ex=null;if(!string.IsNullOrWhiteSpace(r.Comanda))ex=data.Invoices.FirstOrDefault(x=>x.Year==r.Year&&Norm(x.Comanda)==Norm(r.Comanda));if(ex==null)ex=data.Invoices.FirstOrDefault(x=>x.Year==r.Year&&Norm(x.Factura)==Norm(r.Factura)&&Norm(x.Transportator)==Norm(r.Transportator));if(ex!=null){ex.NrCrt=r.NrCrt;ex.Comanda=r.Comanda;ex.Factura=r.Factura;ex.Transportator=r.Transportator;ex.TotalLei=r.TotalLei;ex.TotalEur=r.TotalEur;ex.Iban=r.Iban;ex.DataPrimire=r.DataPrimire;ex.ZileScadenta=r.ZileScadenta;ex.Scadenta=r.Scadenta;ex.ScadentaText=r.ScadentaText;ex.ScadentaInvalida=r.ScadentaInvalida;ex.DataPlatii=r.DataPlatii;ex.Observatii=r.Observatii;updated++;}else{data.Invoices.Add(r);added++;}if(!data.Years.Contains(r.Year))data.Years.Add(r.Year);}foreach(var grp in rows.GroupBy(x=>x.Year)){int n=1;foreach(var r in grp){Invoice ex=null;if(!string.IsNullOrWhiteSpace(r.Comanda))ex=data.Invoices.FirstOrDefault(x=>x.Year==grp.Key&&Norm(x.Comanda)==Norm(r.Comanda));if(ex==null)ex=data.Invoices.FirstOrDefault(x=>x.Year==grp.Key&&Norm(x.Factura)==Norm(r.Factura)&&Norm(x.Transportator)==Norm(r.Transportator));if(ex!=null){ex.NrCrt=n;repaired++;}n++;}}SaveData();RefreshAll();MessageBox.Show("Import finalizat. Adaugate: "+added+" | Actualizate: "+updated+" | NR. CRT. reparate: "+repaired+".\n\nNR. CRT. este generat 1, 2, 3... dupa ordinea randurilor din Excel; formulele din coloana NR. CRT. sunt ignorate complet. Scadenta din Excel este pastrata exact; datele calendaristice imposibile sunt marcate DATA INVALIDA.");}catch(Exception ex){MessageBox.Show("Importul nu a reusit: "+ex.Message);}}
 string Norm(string s){return (s??"").Trim().ToUpperInvariant();}
}

public class InvoiceForm:Form{public Invoice Result;TextBox nr,tr,co,fa,lei,eur,iban,obs,zile;DateTimePicker prim,scad;int year;public InvoiceForm(Invoice x,int y,int nextNr){year=y;Text=x==null?"Factura noua":"Modifica factura";Width=520;Height=560;StartPosition=FormStartPosition.CenterParent;var p=new TableLayoutPanel{Dock=DockStyle.Fill,ColumnCount=2,Padding=new Padding(12),AutoScroll=true};p.ColumnStyles.Add(new ColumnStyle(SizeType.Absolute,170));p.ColumnStyles.Add(new ColumnStyle(SizeType.Percent,100));Controls.Add(p);nr=Add(p,"NR. CRT.");nr.Text=nextNr.ToString();tr=Add(p,"Transportator");co=Add(p,"Comanda");fa=Add(p,"Factura / Data");lei=Add(p,"Total factura LEI");eur=Add(p,"Total EUR");iban=Add(p,"IBAN");prim=AddDate(p,"Data primirii");zile=Add(p,"Scadenta (zile)");zile.Text="30";scad=AddDate(p,"Data scadenta");obs=Add(p,"Observatii");prim.ValueChanged+=(s,e)=>Calc();zile.TextChanged+=(s,e)=>Calc();var b=new Button{Text="Salveaza",Dock=DockStyle.Fill,Height=34};b.Click+=(s,e)=>Save();p.Controls.Add(new Label());p.Controls.Add(b);if(x!=null){nr.Text=x.NrCrt.ToString();tr.Text=x.Transportator;co.Text=x.Comanda;fa.Text=x.Factura;lei.Text=x.TotalLei.ToString();eur.Text=x.TotalEur.ToString();iban.Text=x.Iban;prim.Value=x.DataPrimire;zile.Text=x.ZileScadenta.ToString();scad.Value=x.Scadenta;obs.Text=x.Observatii;Result=x;}}
 TextBox Add(TableLayoutPanel p,string l){p.RowCount++;p.RowStyles.Add(new RowStyle(SizeType.Absolute,38));p.Controls.Add(new Label{Text=l,AutoSize=true,Padding=new Padding(0,8,0,0)});var t=new TextBox{Dock=DockStyle.Fill};p.Controls.Add(t);return t;}DateTimePicker AddDate(TableLayoutPanel p,string l){p.RowCount++;p.RowStyles.Add(new RowStyle(SizeType.Absolute,38));p.Controls.Add(new Label{Text=l,AutoSize=true,Padding=new Padding(0,8,0,0)});var d=new DateTimePicker{Format=DateTimePickerFormat.Custom,CustomFormat="dd.MM.yyyy",Dock=DockStyle.Fill};p.Controls.Add(d);return d;}void Calc(){int z;if(int.TryParse(zile.Text,out z))scad.Value=prim.Value.Date.AddDays(z);}decimal Dec(string s){decimal v;decimal.TryParse((s??"").Replace(" ","").Replace(",","."),NumberStyles.Any,CultureInfo.InvariantCulture,out v);return v;}void Save(){int z;if(!int.TryParse(zile.Text,out z))z=0;int nrc;if(!int.TryParse(nr.Text,out nrc)||nrc<=0){MessageBox.Show("NR. CRT. trebuie sa fie un numar mai mare ca 0.");return;}Result=new Invoice{Year=year,NrCrt=nrc,Transportator=tr.Text.Trim(),Comanda=co.Text.Trim(),Factura=fa.Text.Trim(),TotalLei=Dec(lei.Text),TotalEur=Dec(eur.Text),Iban=iban.Text.Trim(),DataPrimire=prim.Value.Date,ZileScadenta=z,Scadenta=scad.Value.Date,ScadentaText=scad.Value.Date.ToString("dd.MM.yyyy"),ScadentaInvalida=false,Observatii=obs.Text.Trim(),DataPlatii=Result==null?null:Result.DataPlatii};DialogResult=DialogResult.OK;Close();}}
public class DateDialog:Form{DateTimePicker d;public DateTime Value{get{return d.Value.Date;}}public DateDialog(string title,DateTime val){Text=title;Width=300;Height=140;StartPosition=FormStartPosition.CenterParent;d=new DateTimePicker{Format=DateTimePickerFormat.Custom,CustomFormat="dd.MM.yyyy",Value=val,Left=20,Top=15,Width=240};var b=new Button{Text="OK",Left=170,Top=52,Width=90};b.Click+=(s,e)=>{DialogResult=DialogResult.OK;Close();};Controls.Add(d);Controls.Add(b);}}

public static class XlsxReader{
 public static List<Invoice> Read(string path){var all=new List<Invoice>();using(var z=ZipFile.OpenRead(path)){var shared=ReadShared(z);var wb=XDocument.Load(z.GetEntry("xl/workbook.xml").Open());XNamespace ns="http://schemas.openxmlformats.org/spreadsheetml/2006/main";XNamespace rel="http://schemas.openxmlformats.org/officeDocument/2006/relationships";var rels=XDocument.Load(z.GetEntry("xl/_rels/workbook.xml.rels").Open());XNamespace rns="http://schemas.openxmlformats.org/package/2006/relationships";foreach(var sh in wb.Descendants(ns+"sheet")){int year;if(!int.TryParse((string)sh.Attribute("name"),out year))continue;string rid=(string)sh.Attribute(rel+"id");var rr=rels.Descendants(rns+"Relationship").FirstOrDefault(x=>(string)x.Attribute("Id")==rid);if(rr==null)continue;string target=(string)rr.Attribute("Target");if(target.StartsWith("/"))target=target.TrimStart('/');else target="xl/"+target.Replace("../","");var en=z.GetEntry(target);if(en==null)continue;all.AddRange(ReadSheet(en,shared,year));}}return all;}
 static List<string> ReadShared(ZipArchive z){var l=new List<string>();var e=z.GetEntry("xl/sharedStrings.xml");if(e==null)return l;var d=XDocument.Load(e.Open());XNamespace n="http://schemas.openxmlformats.org/spreadsheetml/2006/main";foreach(var si in d.Descendants(n+"si"))l.Add(string.Concat(si.Descendants(n+"t").Select(x=>x.Value)));return l;}
 static List<Invoice> ReadSheet(ZipArchiveEntry e,List<string> ss,int year){var outp=new List<Invoice>();var d=XDocument.Load(e.Open());XNamespace n="http://schemas.openxmlformats.org/spreadsheetml/2006/main";var rows=d.Descendants(n+"row").ToList();if(rows.Count<2)return outp;Dictionary<int,string> headers=null;foreach(var row in rows){var vals=Cells(row,n,ss);if(headers==null){headers=vals.ToDictionary(k=>k.Key,k=>(k.Value??"").Trim().ToUpperInvariant());if(!headers.Values.Any(x=>x.Contains("TRANSPORT"))){headers=null;continue;}continue;}string tr=By(vals,headers,"TRANSPORT"), fact=By(vals,headers,"FACTUR");if(string.IsNullOrWhiteSpace(tr)&&string.IsNullOrWhiteSpace(fact))continue; int nr=outp.Count+1; // NR. CRT. urmeaza ordinea fizica a randurilor din Excel.
DateTime prim=Date(By(vals,headers,"PR.PLICULUI","PRIMIR")); string scRaw=ByExact(vals,headers,"SCADENTA"); DateTime sc=Date(scRaw); bool scInvalid=!string.IsNullOrWhiteSpace(scRaw)&&sc.Year<2000; if(string.IsNullOrWhiteSpace(scRaw)){scRaw=By(vals,headers,"SCADENTA RECALCULATA");sc=Date(scRaw);scInvalid=!string.IsNullOrWhiteSpace(scRaw)&&sc.Year<2000;} if(string.IsNullOrWhiteSpace(scRaw)&&prim.Year>2000){sc=prim.AddDays(30);scRaw=sc.ToString("dd.MM.yyyy");scInvalid=false;} var inv=new Invoice{Year=year,NrCrt=nr,Transportator=tr,Comanda=By(vals,headers,"COMAND"),Factura=fact,TotalLei=Num(By(vals,headers,"TOTAL FACT/LEI","TOTAL FACTURA LEI","TOTAL LEI","TOTAL/LEI")),TotalEur=Num(By(vals,headers,"TOTAL/ EURO","TOTAL/EURO","TOTAL EUR","TOTAL EURO")),Iban=By(vals,headers,"IBAN"),DataPrimire=prim.Year>2000?prim:DateTime.Today,Scadenta=sc.Year>2000?sc:DateTime.MinValue,ScadentaText=NormalizeDateText(scRaw,sc),ScadentaInvalida=scInvalid,Observatii=By(vals,headers,"OBSERV")};var pay=Date(By(vals,headers,"DATA PLAT"));if(pay.Year>2000)inv.DataPlatii=pay;inv.ZileScadenta=inv.ScadentaInvalida?0:(inv.Scadenta-inv.DataPrimire).Days;outp.Add(inv);}return outp;}
 static Dictionary<int,string> Cells(XElement row,XNamespace n,List<string> ss){var m=new Dictionary<int,string>();foreach(var c in row.Elements(n+"c")){string r=(string)c.Attribute("r")??"A1";int col=Col(r);string t=(string)c.Attribute("t");string v=(string)c.Element(n+"v")??"";if(t=="s"){int i;if(int.TryParse(v,out i)&&i>=0&&i<ss.Count)v=ss[i];}else if(t=="inlineStr")v=string.Concat(c.Descendants(n+"t").Select(x=>x.Value));m[col]=v;}return m;}static int Col(string r){int x=0;foreach(char c in r){if(!char.IsLetter(c))break;x=x*26+(char.ToUpperInvariant(c)-'A'+1);}return x;}static string ByExact(Dictionary<int,string> v,Dictionary<int,string> h,string key){var q=h.FirstOrDefault(x=>x.Value==key);return q.Value!=null&&v.ContainsKey(q.Key)?v[q.Key]:"";}static string By(Dictionary<int,string> v,Dictionary<int,string> h,params string[] keys){foreach(var k in keys){var q=h.FirstOrDefault(x=>x.Value.Contains(k));if(q.Value!=null&&v.ContainsKey(q.Key))return v[q.Key];}return "";}static int IntNum(string s){int x;if(int.TryParse((s??"").Trim(),out x))return x;double d;if(double.TryParse((s??"").Trim(),NumberStyles.Any,CultureInfo.InvariantCulture,out d))return (int)d;return 0;}static decimal Num(string s){decimal x;decimal.TryParse((s??"").Replace(" ","").Replace(",","."),NumberStyles.Any,CultureInfo.InvariantCulture,out x);return x;}static string NormalizeDateText(string raw,DateTime parsed){if(string.IsNullOrWhiteSpace(raw))return ""; double o;if(double.TryParse(raw,NumberStyles.Any,CultureInfo.InvariantCulture,out o)&&o>20000&&o<80000&&parsed.Year>2000)return parsed.ToString("dd.MM.yyyy");return raw.Trim();}static DateTime Date(string s){double o;if(double.TryParse(s,NumberStyles.Any,CultureInfo.InvariantCulture,out o)&&o>20000&&o<80000)return DateTime.FromOADate(o);DateTime d;string[] f={"dd.MM.yyyy","d.M.yyyy","dd/MM/yyyy","d/M/yyyy","yyyy-MM-dd"};return DateTime.TryParseExact(s,f,CultureInfo.InvariantCulture,DateTimeStyles.None,out d)?d:DateTime.MinValue;}
}
static class Program{[STAThread]static void Main(){
 try{
  Application.EnableVisualStyles(); Application.SetCompatibleTextRenderingDefault(false); Application.Run(new MainForm());
 }catch(Exception ex){
  try{string dir=Path.Combine(Environment.GetFolderPath(Environment.SpecialFolder.MyDocuments),"ScadentarTransportatori");Directory.CreateDirectory(dir);File.WriteAllText(Path.Combine(dir,"eroare.log"),DateTime.Now.ToString("s")+Environment.NewLine+ex.ToString());}catch{}
  MessageBox.Show("Aplicatia nu a putut porni. Detaliile au fost salvate in Documents\\ScadentarTransportatori\\eroare.log\n\n"+ex.Message,"Scadentar Transportatori - Eroare",MessageBoxButtons.OK,MessageBoxIcon.Error);
 }
}}
}
