using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Drawing;
using System.Globalization;
using System.IO;
using System.IO.Compression;
using System.Linq;
using System.Windows.Forms;
using System.Xml.Linq;
using System.Xml.Serialization;

namespace ScadentarTransportatori {
[Serializable] public class Invoice {
 public int Year; public int NrCrt; public string Transportator=""; public string Comanda=""; public string Factura=""; public decimal TotalLei; public decimal TotalEur; public string Iban=""; public DateTime DataPrimire=DateTime.Today; public int ZileScadenta=30; public DateTime Scadenta=DateTime.Today.AddDays(30); public string ScadentaText=""; public bool ScadentaInvalida=false; public DateTime? DataPlatii; public string Observatii="";
 public bool Platita { get { return DataPlatii.HasValue; } }
}
[Serializable] public class AppData { public List<int> Years=new List<int>(); public List<Invoice> Invoices=new List<Invoice>(); }

public class MainForm:Form {
 AppData data; string baseDir, dbFile, backupDir; ComboBox yearBox, transportBox; TextBox transportSearch; DataGridView grid; Label lblDue,lblTotal,lblTotalEur,lblDueEur,lblOld,lblCount; BindingList<Invoice> view=new BindingList<Invoice>(); bool refreshingYear=false, refreshingTransport=false, onlyDue=false; Button btnDue; DashboardChart chartMonthly, chartStatus, chartTop;
 public MainForm(){ Text="OTL - Scadentar Facturi Transportatori v2.4"; Width=1540; Height=900; MinimumSize=new Size(1200,700); BackColor=Color.FromArgb(236,242,247); StartPosition=FormStartPosition.CenterScreen; Font=new Font("Segoe UI",9F); baseDir=Path.Combine(Environment.GetFolderPath(Environment.SpecialFolder.MyDocuments),"ScadentarTransportatori"); dbFile=Path.Combine(baseDir,"scadentar.xml"); backupDir=Path.Combine(baseDir,"Backup"); Directory.CreateDirectory(baseDir); Directory.CreateDirectory(backupDir); LoadData(); BuildUi(); RefreshAll(); AutoBackup(); }
 void BuildUi(){
  Text="OTL Scadentar 4.1 - Control Financiar";
  var root=new TableLayoutPanel{Dock=DockStyle.Fill,ColumnCount=1,RowCount=5,Padding=new Padding(0),BackColor=Color.FromArgb(235,241,247)};
  root.RowStyles.Add(new RowStyle(SizeType.Absolute,100)); root.RowStyles.Add(new RowStyle(SizeType.Absolute,86)); root.RowStyles.Add(new RowStyle(SizeType.Absolute,58)); root.RowStyles.Add(new RowStyle(SizeType.Absolute,190)); root.RowStyles.Add(new RowStyle(SizeType.Percent,100)); Controls.Add(root);

  var header=new Panel{Dock=DockStyle.Fill,BackColor=Color.FromArgb(7,29,49),Padding=new Padding(22,10,22,8)}; root.Controls.Add(header,0,0);
  var logo=new Label{Text="OTL",ForeColor=Color.White,Font=new Font("Segoe UI",31F,FontStyle.Bold|FontStyle.Italic),AutoSize=true,Left=24,Top=9}; header.Controls.Add(logo);
  var company=new Label{Text="OCTAV TRANSPORT LOGISTIC",ForeColor=Color.FromArgb(157,190,216),Font=new Font("Segoe UI",9F,FontStyle.Bold),AutoSize=true,Left=28,Top=64}; header.Controls.Add(company);
  var sep=new Panel{BackColor=Color.FromArgb(35,137,201),Left=210,Top=15,Width=3,Height=67}; header.Controls.Add(sep);
  var title=new Label{Text="SCADENTAR • CONTROL FINANCIAR TRANSPORTATORI",ForeColor=Color.White,Font=new Font("Segoe UI",20F,FontStyle.Bold),AutoSize=true,Left=232,Top=14}; header.Controls.Add(title);
  var sub=new Label{Text="Dashboard operational  |  Scadente  |  Plati  |  Parteneri transport",ForeColor=Color.FromArgb(164,196,218),Font=new Font("Segoe UI",10F),AutoSize=true,Left=235,Top=57}; header.Controls.Add(sub);
  var badge=new Label{Text="● SISTEM OTL  •  v4.1",ForeColor=Color.White,BackColor=Color.FromArgb(13,92,145),Font=new Font("Segoe UI",9F,FontStyle.Bold),AutoSize=true,Padding=new Padding(14,8,14,8),Anchor=AnchorStyles.Top|AnchorStyles.Right}; badge.Top=27;header.Controls.Add(badge);header.Resize+=(s,e)=>badge.Left=header.ClientSize.Width-badge.Width-24;

  var stats=new FlowLayoutPanel{Dock=DockStyle.Fill,Padding=new Padding(12,8,8,7),WrapContents=false,AutoScroll=true,BackColor=Color.FromArgb(222,231,239)};
  lblTotal=Stat(stats,"TOTAL DE PLATA LEI",Color.FromArgb(18,93,142)); lblTotalEur=Stat(stats,"TOTAL DE PLATA EUR",Color.FromArgb(29,113,159)); lblDue=Stat(stats,"TOTAL SCADENT LEI",Color.FromArgb(193,57,69)); lblDueEur=Stat(stats,"TOTAL SCADENT EUR",Color.FromArgb(215,91,50)); lblCount=Stat(stats,"FACTURI NEPLATITE",Color.FromArgb(106,74,148)); lblOld=Stat(stats,"RESTANTE ANI ANTERIORI",Color.FromArgb(75,91,105)); root.Controls.Add(stats,0,1);

  var top=new FlowLayoutPanel{Dock=DockStyle.Fill,Padding=new Padding(12,12,8,7),WrapContents=false,AutoScroll=true,BackColor=Color.White};
  top.Controls.Add(new Label{Text="AN",ForeColor=Color.FromArgb(45,62,75),Font=new Font("Segoe UI",9F,FontStyle.Bold),AutoSize=true,Padding=new Padding(0,8,2,0)}); yearBox=new ComboBox{DropDownStyle=ComboBoxStyle.DropDownList,Width=84,Height=32}; yearBox.SelectedIndexChanged+=(s,e)=>{if(!refreshingYear)RefreshAll();}; top.Controls.Add(yearBox);
  top.Controls.Add(new Label{Text="TRANSPORTATOR",ForeColor=Color.FromArgb(45,62,75),Font=new Font("Segoe UI",9F,FontStyle.Bold),AutoSize=true,Padding=new Padding(12,8,2,0)}); transportBox=new ComboBox{DropDownStyle=ComboBoxStyle.DropDownList,Width=205,Height=32}; transportBox.SelectedIndexChanged+=(s,e)=>{if(!refreshingTransport)RefreshViewAndTotals();}; top.Controls.Add(transportBox);
  transportSearch=new TextBox{Width=165,Height=32,Margin=new Padding(4,3,8,0)}; transportSearch.TextChanged+=(s,e)=>RefreshViewAndTotals(); top.Controls.Add(transportSearch);
  AddButton(top,"CLIENTI • DE INCASAT",(s,e)=>{using(var f=new ReceivablesForm(baseDir))f.ShowDialog(this);},true); AddButton(top,"+ AN",(s,e)=>AddYear(),false); AddButton(top,"+ FACTURA NOUA",(s,e)=>EditInvoice(null),true); btnDue=AddButton(top,"DOAR SCADENTE",(s,e)=>ToggleDue(),false); AddButton(top,"MARCAJ PLATITA",(s,e)=>MarkPaid(),false); AddButton(top,"IMPORT EXCEL",(s,e)=>ImportExcel(),false); AddButton(top,"EXPORT CSV",(s,e)=>ExportCsv(),false); AddButton(top,"BACKUP",(s,e)=>{Backup(); MessageBox.Show("Backup creat.");},false); AddButton(top,"RESTAUREAZA",(s,e)=>Restore(),false); root.Controls.Add(top,0,2);

  var dash=new TableLayoutPanel{Dock=DockStyle.Fill,ColumnCount=3,RowCount=1,Padding=new Padding(12,7,12,8),BackColor=Color.FromArgb(235,241,247)}; dash.ColumnStyles.Add(new ColumnStyle(SizeType.Percent,38));dash.ColumnStyles.Add(new ColumnStyle(SizeType.Percent,25));dash.ColumnStyles.Add(new ColumnStyle(SizeType.Percent,37));root.Controls.Add(dash,0,3);
  chartMonthly=new DashboardChart{Dock=DockStyle.Fill,Title="EVOLUTIE LUNARA • LEI",ChartKind=0,Margin=new Padding(0,0,8,0)};chartStatus=new DashboardChart{Dock=DockStyle.Fill,Title="SITUATIE FACTURI",ChartKind=1,Margin=new Padding(0,0,8,0)};chartTop=new DashboardChart{Dock=DockStyle.Fill,Title="TOP TRANSPORTATORI • NEPLATIT",ChartKind=2};dash.Controls.Add(chartMonthly,0,0);dash.Controls.Add(chartStatus,1,0);dash.Controls.Add(chartTop,2,0);

  var gridHost=new Panel{Dock=DockStyle.Fill,Padding=new Padding(12,4,12,12),BackColor=Color.FromArgb(235,241,247)}; root.Controls.Add(gridHost,0,4);
  grid=new DataGridView{Dock=DockStyle.Fill,AutoGenerateColumns=false,ReadOnly=true,AllowUserToAddRows=false,SelectionMode=DataGridViewSelectionMode.FullRowSelect,MultiSelect=false,RowHeadersVisible=false,AutoSizeColumnsMode=DataGridViewAutoSizeColumnsMode.Fill,ColumnHeadersVisible=true,ColumnHeadersHeight=42,ColumnHeadersHeightSizeMode=DataGridViewColumnHeadersHeightSizeMode.DisableResizing,EnableHeadersVisualStyles=false,BackgroundColor=Color.White,BorderStyle=BorderStyle.FixedSingle,GridColor=Color.FromArgb(220,227,233),RowTemplate={Height=31}};
  grid.ColumnHeadersDefaultCellStyle.Font=new Font("Segoe UI",9F,FontStyle.Bold); grid.ColumnHeadersDefaultCellStyle.Alignment=DataGridViewContentAlignment.MiddleCenter; grid.ColumnHeadersDefaultCellStyle.BackColor=Color.FromArgb(8,55,88); grid.ColumnHeadersDefaultCellStyle.ForeColor=Color.White; grid.DefaultCellStyle.SelectionBackColor=Color.FromArgb(194,221,239);grid.DefaultCellStyle.SelectionForeColor=Color.Black;grid.AlternatingRowsDefaultCellStyle.BackColor=Color.FromArgb(247,249,251); gridHost.Controls.Add(grid);
  string[] heads={"NR. CRT.","TRANSPORTATOR","COMANDA","FACTURA / DATA","TOTAL LEI","TOTAL EUR","IBAN","DATA PRIMIRE","SCADENTA","ZILE INTARZIERE","DATA PLATII","OBSERVATII"}; string[] props={"NrCrt","Transportator","Comanda","Factura","TotalLei","TotalEur","Iban","DataPrimire","Scadenta","Delay","DataPlatii","Observatii"};
  for(int i=0;i<heads.Length;i++){ var c=new DataGridViewTextBoxColumn{HeaderText=heads[i],Name=props[i],SortMode=DataGridViewColumnSortMode.NotSortable}; grid.Columns.Add(c); } grid.Columns[0].FillWeight=42; grid.Columns[1].FillWeight=115; grid.Columns[6].FillWeight=120;
  grid.CellDoubleClick+=(s,e)=>{ if(e.RowIndex>=0) EditInvoice(view[e.RowIndex]);}; grid.CellFormatting+=FormatCell;
 }
 Button AddButton(Control p,string t,EventHandler h,bool primary){var b=new Button{Text=t,AutoSize=true,Height=34,FlatStyle=FlatStyle.Standard,BackColor=primary?Color.FromArgb(19,126,184):Color.FromArgb(232,239,245),ForeColor=primary?Color.White:Color.FromArgb(18,55,78),Font=new Font("Segoe UI",8.5F,FontStyle.Bold),Margin=new Padding(4,0,4,0),Padding=new Padding(9,0,9,0),Cursor=Cursors.Hand,UseVisualStyleBackColor=false};b.FlatAppearance.BorderSize=1;b.Click+=h;p.Controls.Add(b);return b;}
 Label Stat(Control p,string title,Color color){var l=new Label{Text=title+"\n0",Width=225,Height=62,BackColor=color,ForeColor=Color.White,TextAlign=ContentAlignment.MiddleCenter,Font=new Font("Segoe UI",10F,FontStyle.Bold),Margin=new Padding(4),Padding=new Padding(4),BorderStyle=BorderStyle.FixedSingle};p.Controls.Add(l);return l;}
 void LoadData(){ try{if(File.Exists(dbFile)){using(var f=File.OpenRead(dbFile)) data=(AppData)new XmlSerializer(typeof(AppData)).Deserialize(f);}else data=new AppData();}catch{data=new AppData();} if(data.Years.Count==0)data.Years.Add(DateTime.Today.Year);}
 void SaveData(){Directory.CreateDirectory(baseDir);using(var f=File.Create(dbFile))new XmlSerializer(typeof(AppData)).Serialize(f,data);}
 int CurrentYear(){int y;return int.TryParse(yearBox.SelectedItem==null?"":yearBox.SelectedItem.ToString(),out y)?y:DateTime.Today.Year;}
 void RefreshAll(){int sel=CurrentYear(); refreshingYear=true; try{ yearBox.Items.Clear(); foreach(var y in data.Years.Distinct().OrderByDescending(x=>x))yearBox.Items.Add(y.ToString()); var target=data.Years.Contains(sel)?sel:data.Years.Max(); yearBox.SelectedItem=target.ToString(); RefreshTransporters(target); RefreshViewAndTotals(); } finally { refreshingYear=false; }}
 void RefreshTransporters(int year){string prev=transportBox==null||transportBox.SelectedItem==null?"Toti transportatorii":transportBox.SelectedItem.ToString(); refreshingTransport=true; try{transportBox.Items.Clear();transportBox.Items.Add("Toti transportatorii");foreach(var t in data.Invoices.Where(x=>x.Year==year&&!string.IsNullOrWhiteSpace(x.Transportator)).Select(x=>x.Transportator.Trim()).Distinct(StringComparer.CurrentCultureIgnoreCase).OrderBy(x=>x))transportBox.Items.Add(t);int idx=transportBox.FindStringExact(prev);transportBox.SelectedIndex=idx>=0?idx:0;}finally{refreshingTransport=false;}}
 IEnumerable<Invoice> FilteredCurrentYear(){int y=CurrentYear();IEnumerable<Invoice> q=data.Invoices.Where(x=>x.Year==y);string tr=transportBox==null||transportBox.SelectedIndex<=0?"":transportBox.SelectedItem.ToString();if(!string.IsNullOrWhiteSpace(tr))q=q.Where(x=>string.Equals((x.Transportator??"").Trim(),tr.Trim(),StringComparison.CurrentCultureIgnoreCase));string search=transportSearch==null?"":transportSearch.Text.Trim();if(search.Length>0)q=q.Where(x=>(x.Transportator??"").IndexOf(search,StringComparison.CurrentCultureIgnoreCase)>=0);if(onlyDue)q=q.Where(x=>!x.Platita&&!x.ScadentaInvalida&&x.Scadenta.Date<=DateTime.Today.Date);return q;}
 void RefreshViewAndTotals(){if(grid==null||yearBox==null||yearBox.SelectedItem==null)return;var filtered=FilteredCurrentYear().ToList();view=new BindingList<Invoice>(filtered.OrderBy(x=>x.NrCrt<=0?int.MaxValue:x.NrCrt).ThenBy(x=>x.NrCrt).ToList());grid.Rows.Clear();foreach(var x in view){int delay=!x.Platita&&!x.ScadentaInvalida&&DateTime.Today.Date>x.Scadenta.Date?(DateTime.Today.Date-x.Scadenta.Date).Days:0;string scText=x.ScadentaInvalida?((string.IsNullOrWhiteSpace(x.ScadentaText)?"DATA INVALIDA":x.ScadentaText)+" - DATA INVALIDA"):(!string.IsNullOrWhiteSpace(x.ScadentaText)?x.ScadentaText:x.Scadenta.ToString("dd.MM.yyyy"));grid.Rows.Add(x.NrCrt,x.Transportator,x.Comanda,x.Factura,x.TotalLei.ToString("N2"),x.TotalEur.ToString("N2"),x.Iban,x.DataPrimire.ToString("dd.MM.yyyy"),scText,x.ScadentaInvalida?"-":delay.ToString(),x.DataPlatii.HasValue?x.DataPlatii.Value.ToString("dd.MM.yyyy"):"",x.Observatii);}var unpaid=filtered.Where(x=>!x.Platita).ToList();var due=unpaid.Where(x=>!x.ScadentaInvalida&&x.Scadenta.Date<=DateTime.Today.Date).ToList();int target=CurrentYear();var old=data.Invoices.Where(x=>x.Year<target&&!x.Platita&&!x.ScadentaInvalida&&x.Scadenta.Date<=DateTime.Today.Date);lblTotal.Text="TOTAL DE PLATA LEI\n"+unpaid.Sum(x=>x.TotalLei).ToString("N2")+" LEI";lblTotalEur.Text="TOTAL DE PLATA EUR\n"+unpaid.Sum(x=>x.TotalEur).ToString("N2")+" EUR";lblDue.Text="TOTAL SCADENT LEI\n"+due.Sum(x=>x.TotalLei).ToString("N2")+" LEI";lblDueEur.Text="TOTAL SCADENT EUR\n"+due.Sum(x=>x.TotalEur).ToString("N2")+" EUR";lblOld.Text="RESTANTE ANI ANTERIORI\n"+old.Sum(x=>x.TotalLei).ToString("N2")+" LEI / "+old.Sum(x=>x.TotalEur).ToString("N2")+" EUR";lblCount.Text="FACTURI NEPLATITE\n"+unpaid.Count;UpdateDashboard(filtered);}

 void UpdateDashboard(List<Invoice> filtered){
  if(chartMonthly==null)return;
  var month=new decimal[12];foreach(var x in filtered.Where(x=>!x.Platita)){int m=(x.ScadentaInvalida?x.DataPrimire:x.Scadenta).Month;if(m>=1&&m<=12)month[m-1]+=x.TotalLei;}chartMonthly.Values=month.Select(x=>(double)x).ToArray();chartMonthly.Labels=new[]{"IAN","FEB","MAR","APR","MAI","IUN","IUL","AUG","SEP","OCT","NOV","DEC"};
  double paid=filtered.Where(x=>x.Platita).Sum(x=>(double)x.TotalLei), due=filtered.Where(x=>!x.Platita&&!x.ScadentaInvalida&&x.Scadenta.Date<=DateTime.Today.Date).Sum(x=>(double)x.TotalLei), future=filtered.Where(x=>!x.Platita&&(x.ScadentaInvalida||x.Scadenta.Date>DateTime.Today.Date)).Sum(x=>(double)x.TotalLei);chartStatus.Values=new[]{paid,due,future};chartStatus.Labels=new[]{"PLATITE","SCADENTE","IN TERMEN"};
  var top=filtered.Where(x=>!x.Platita).GroupBy(x=>string.IsNullOrWhiteSpace(x.Transportator)?"FARA NUME":x.Transportator).Select(g=>new{N=g.Key,V=g.Sum(x=>(double)x.TotalLei)}).OrderByDescending(x=>x.V).Take(5).ToList();chartTop.Values=top.Select(x=>x.V).ToArray();chartTop.Labels=top.Select(x=>x.N.Length>18?x.N.Substring(0,18)+"…":x.N).ToArray();chartMonthly.Invalidate();chartStatus.Invalidate();chartTop.Invalidate();
 }

 void ToggleDue(){onlyDue=!onlyDue;if(btnDue!=null){btnDue.Text=onlyDue?"AFISEAZA TOATE":"DOAR SCADENTE";btnDue.BackColor=onlyDue?Color.FromArgb(196,52,69):Color.FromArgb(12,102,157);}RefreshViewAndTotals();}

 void FormatCell(object s,DataGridViewCellFormattingEventArgs e){if(e.RowIndex<0||e.RowIndex>=view.Count)return;var x=view[e.RowIndex]; if(x.Platita){grid.Rows[e.RowIndex].DefaultCellStyle.BackColor=Color.Honeydew;return;} if(x.ScadentaInvalida){grid.Rows[e.RowIndex].DefaultCellStyle.BackColor=Color.MistyRose;return;} int d=(DateTime.Today.Date-x.Scadenta.Date).Days; if(d>=1&&d<=10)grid.Rows[e.RowIndex].DefaultCellStyle.BackColor=Color.Khaki; else if(d>=11&&d<=20)grid.Rows[e.RowIndex].DefaultCellStyle.BackColor=Color.Orange; else if(d>20)grid.Rows[e.RowIndex].DefaultCellStyle.BackColor=Color.LightCoral;}
 void AddYear(){string v=Microsoft.VisualBasic.Interaction.InputBox("Introdu anul nou:","Adauga an",(data.Years.Max()+1).ToString());int y;if(int.TryParse(v,out y)&&y>=2000&&y<=2200&&!data.Years.Contains(y)){data.Years.Add(y);SaveData();RefreshAll();yearBox.SelectedItem=y.ToString();}}
 void EditInvoice(Invoice inv){var f=new InvoiceForm(inv,CurrentYear(), inv==null ? NextNrCrt(CurrentYear()) : inv.NrCrt);if(f.ShowDialog()==DialogResult.OK){if(inv==null)data.Invoices.Add(f.Result);else{int i=data.Invoices.IndexOf(inv);data.Invoices[i]=f.Result;} if(!data.Years.Contains(f.Result.Year))data.Years.Add(f.Result.Year);SaveData();RefreshAll();}}
 int NextNrCrt(int year){var nums=data.Invoices.Where(x=>x.Year==year&&x.NrCrt>0).Select(x=>x.NrCrt);return nums.Any()?nums.Max()+1:1;}
 void MarkPaid(){if(grid.SelectedRows.Count==0)return;int i=grid.SelectedRows[0].Index;if(i<0||i>=view.Count)return;var x=view[i];if(x.Platita){MessageBox.Show("Factura este deja marcata ca platita.");return;}using(var d=new DateDialog("Data platii",DateTime.Today)){if(d.ShowDialog()==DialogResult.OK){x.DataPlatii=d.Value;SaveData();RefreshAll();}}}
 void Backup(){if(!File.Exists(dbFile))SaveData();File.Copy(dbFile,Path.Combine(backupDir,"scadentar_"+DateTime.Now.ToString("yyyyMMdd_HHmmss")+".xml"),true);} void AutoBackup(){try{Backup();}catch{}}
 void Restore(){var o=new OpenFileDialog{InitialDirectory=backupDir,Filter="Backup XML|*.xml"};if(o.ShowDialog()!=DialogResult.OK)return;if(MessageBox.Show("Baza curenta va fi inlocuita. Continui?","Restaurare",MessageBoxButtons.YesNo)!=DialogResult.Yes)return;File.Copy(o.FileName,dbFile,true);LoadData();RefreshAll();}
 void ExportCsv(){var s=new SaveFileDialog{Filter="CSV|*.csv",FileName="Scadentar_"+CurrentYear()+".csv"};if(s.ShowDialog()!=DialogResult.OK)return;using(var w=new StreamWriter(s.FileName,false,System.Text.Encoding.UTF8)){w.WriteLine("NR. CRT.;Transportator;Comanda;Factura;Total LEI;Total EUR;IBAN;Data primire;Scadenta;Data platii;Observatii");foreach(var x in data.Invoices.Where(z=>z.Year==CurrentYear()))w.WriteLine(string.Join(";",new[]{x.NrCrt.ToString(),Q(x.Transportator),Q(x.Comanda),Q(x.Factura),x.TotalLei.ToString(CultureInfo.InvariantCulture),x.TotalEur.ToString(CultureInfo.InvariantCulture),Q(x.Iban),x.DataPrimire.ToString("dd.MM.yyyy"),Q(x.ScadentaInvalida?x.ScadentaText:(!string.IsNullOrWhiteSpace(x.ScadentaText)?x.ScadentaText:x.Scadenta.ToString("dd.MM.yyyy"))),x.DataPlatii.HasValue?x.DataPlatii.Value.ToString("dd.MM.yyyy"):"",Q(x.Observatii)}));}MessageBox.Show("Export finalizat.");}
 string Q(string s){return "\""+(s??"").Replace("\"","\"\"")+"\"";}
 void ImportExcel(){var o=new OpenFileDialog{Filter="Excel (*.xlsx)|*.xlsx"};if(o.ShowDialog()!=DialogResult.OK)return;try{var rows=XlsxReader.Read(o.FileName);int added=0,updated=0,repaired=0;foreach(var r in rows){if(string.IsNullOrWhiteSpace(r.Transportator)&&string.IsNullOrWhiteSpace(r.Factura))continue;Invoice ex=null;if(!string.IsNullOrWhiteSpace(r.Comanda))ex=data.Invoices.FirstOrDefault(x=>x.Year==r.Year&&Norm(x.Comanda)==Norm(r.Comanda));if(ex==null)ex=data.Invoices.FirstOrDefault(x=>x.Year==r.Year&&Norm(x.Factura)==Norm(r.Factura)&&Norm(x.Transportator)==Norm(r.Transportator));if(ex!=null){ex.NrCrt=r.NrCrt;ex.Comanda=r.Comanda;ex.Factura=r.Factura;ex.Transportator=r.Transportator;ex.TotalLei=r.TotalLei;ex.TotalEur=r.TotalEur;ex.Iban=r.Iban;ex.DataPrimire=r.DataPrimire;ex.ZileScadenta=r.ZileScadenta;ex.Scadenta=r.Scadenta;ex.ScadentaText=r.ScadentaText;ex.ScadentaInvalida=r.ScadentaInvalida;ex.DataPlatii=r.DataPlatii;ex.Observatii=r.Observatii;updated++;}else{data.Invoices.Add(r);added++;}if(!data.Years.Contains(r.Year))data.Years.Add(r.Year);}foreach(var grp in rows.GroupBy(x=>x.Year)){int n=1;foreach(var r in grp){Invoice ex=null;if(!string.IsNullOrWhiteSpace(r.Comanda))ex=data.Invoices.FirstOrDefault(x=>x.Year==grp.Key&&Norm(x.Comanda)==Norm(r.Comanda));if(ex==null)ex=data.Invoices.FirstOrDefault(x=>x.Year==grp.Key&&Norm(x.Factura)==Norm(r.Factura)&&Norm(x.Transportator)==Norm(r.Transportator));if(ex!=null){ex.NrCrt=n;repaired++;}n++;}}SaveData();RefreshAll();MessageBox.Show("Import finalizat. Adaugate: "+added+" | Actualizate: "+updated+" | NR. CRT. reparate: "+repaired+".\n\nNR. CRT. este generat 1, 2, 3... dupa ordinea randurilor din Excel; formulele din coloana NR. CRT. sunt ignorate complet. Scadenta din Excel este pastrata exact; datele calendaristice imposibile sunt marcate DATA INVALIDA.");}catch(Exception ex){MessageBox.Show("Importul nu a reusit: "+ex.Message);}}
 string Norm(string s){return (s??"").Trim().ToUpperInvariant();}
}


[Serializable] public class ReceivableItem {
 public string Client=""; public string Factura=""; public DateTime DataFactura=DateTime.Today; public decimal SumaInitiala; public decimal Incasat; public DateTime? DataUltimeiIncasari; public string Observatii="";
 public decimal Rest { get { return Math.Max(0,SumaInitiala-Incasat); } }
 public bool Achitata { get { return Rest<=0.005m; } }
}
[Serializable] public class ReceivableData { public List<ReceivableItem> Items=new List<ReceivableItem>(); }

public class ReceivablesForm:Form {
 string file; ReceivableData data; DataGridView grid; Label total,received,count; CheckBox showPaid; TextBox search;
 public ReceivablesForm(string baseDir){file=Path.Combine(baseDir,"clienti_incasari.xml");Text="OTL • CLIENTI - DE INCASAT";Width=1280;Height=760;MinimumSize=new Size(1000,620);StartPosition=FormStartPosition.CenterParent;BackColor=Color.FromArgb(235,241,247);Font=new Font("Segoe UI",9F);LoadData();Build();RefreshGrid();}
 void Build(){var root=new TableLayoutPanel{Dock=DockStyle.Fill,RowCount=4,ColumnCount=1};root.RowStyles.Add(new RowStyle(SizeType.Absolute,82));root.RowStyles.Add(new RowStyle(SizeType.Absolute,82));root.RowStyles.Add(new RowStyle(SizeType.Absolute,56));root.RowStyles.Add(new RowStyle(SizeType.Percent,100));Controls.Add(root);
  var h=new Panel{Dock=DockStyle.Fill,BackColor=Color.FromArgb(7,29,49)};root.Controls.Add(h);h.Controls.Add(new Label{Text="OTL",Left=20,Top=12,AutoSize=true,ForeColor=Color.White,Font=new Font("Segoe UI",27F,FontStyle.Bold|FontStyle.Italic)});h.Controls.Add(new Label{Text="CLIENTI • DE INCASAT",Left=145,Top=16,AutoSize=true,ForeColor=Color.White,Font=new Font("Segoe UI",20F,FontStyle.Bold)});h.Controls.Add(new Label{Text="Solduri clienti, incasari integrale si partiale",Left=148,Top=50,AutoSize=true,ForeColor=Color.FromArgb(164,196,218),Font=new Font("Segoe UI",9.5F)});
  var cards=new FlowLayoutPanel{Dock=DockStyle.Fill,Padding=new Padding(12,8,8,6),WrapContents=false,BackColor=Color.FromArgb(222,231,239)};root.Controls.Add(cards);total=Card(cards,"TOTAL DE INCASAT",Color.FromArgb(18,93,142));received=Card(cards,"INCASAT INREGISTRAT",Color.FromArgb(36,128,92));count=Card(cards,"FACTURI NEINCASATE",Color.FromArgb(193,57,69));
  var bar=new FlowLayoutPanel{Dock=DockStyle.Fill,Padding=new Padding(12,10,8,6),WrapContents=false,BackColor=Color.White};root.Controls.Add(bar);Btn(bar,"+ FACTURA CLIENT",(s,e)=>AddManual(),true);Btn(bar,"INREGISTREAZA INCASARE",(s,e)=>RegisterPayment(),true);Btn(bar,"IMPORT BALANTA CSV",(s,e)=>ImportCsv(),false);Btn(bar,"EXPORT CSV",(s,e)=>ExportCsv(),false);showPaid=new CheckBox{Text="Arata si incasatele",AutoSize=true,Padding=new Padding(8,7,4,0)};showPaid.CheckedChanged+=(s,e)=>RefreshGrid();bar.Controls.Add(showPaid);bar.Controls.Add(new Label{Text="Cauta client:",AutoSize=true,Padding=new Padding(10,8,2,0)});search=new TextBox{Width=190,Margin=new Padding(2,4,4,0)};search.TextChanged+=(s,e)=>RefreshGrid();bar.Controls.Add(search);
  var host=new Panel{Dock=DockStyle.Fill,Padding=new Padding(12),BackColor=Color.FromArgb(235,241,247)};root.Controls.Add(host);grid=new DataGridView{Dock=DockStyle.Fill,ReadOnly=true,AllowUserToAddRows=false,SelectionMode=DataGridViewSelectionMode.FullRowSelect,MultiSelect=false,RowHeadersVisible=false,AutoSizeColumnsMode=DataGridViewAutoSizeColumnsMode.Fill,BackgroundColor=Color.White,EnableHeadersVisualStyles=false,ColumnHeadersHeight=40};grid.ColumnHeadersDefaultCellStyle.BackColor=Color.FromArgb(8,55,88);grid.ColumnHeadersDefaultCellStyle.ForeColor=Color.White;grid.ColumnHeadersDefaultCellStyle.Font=new Font("Segoe UI",9F,FontStyle.Bold);grid.Columns.Add("Client","CLIENT");grid.Columns.Add("Factura","FACTURA");grid.Columns.Add("Data","DATA FACTURA");grid.Columns.Add("Initial","SUMA INITIALA");grid.Columns.Add("Incasat","INCASAT");grid.Columns.Add("Rest","REST DE INCASAT");grid.Columns.Add("Ultima","ULTIMA INCASARE");grid.Columns.Add("Status","STATUS");grid.Columns.Add("Obs","OBSERVATII");host.Controls.Add(grid);
 }
 Label Card(Control p,string t,Color c){var l=new Label{Text=t+"\n0,00 LEI",Width=250,Height=60,BackColor=c,ForeColor=Color.White,TextAlign=ContentAlignment.MiddleCenter,Font=new Font("Segoe UI",10F,FontStyle.Bold),Margin=new Padding(4),BorderStyle=BorderStyle.FixedSingle};p.Controls.Add(l);return l;}
 Button Btn(Control p,string t,EventHandler h,bool primary){var b=new Button{Text=t,AutoSize=true,Height=34,BackColor=primary?Color.FromArgb(19,126,184):Color.FromArgb(232,239,245),ForeColor=primary?Color.White:Color.FromArgb(18,55,78),Font=new Font("Segoe UI",8.5F,FontStyle.Bold),FlatStyle=FlatStyle.Standard,UseVisualStyleBackColor=false,Margin=new Padding(4,0,4,0),Padding=new Padding(8,0,8,0)};b.Click+=h;p.Controls.Add(b);return b;}
 void LoadData(){try{if(File.Exists(file)){using(var f=File.OpenRead(file))data=(ReceivableData)new XmlSerializer(typeof(ReceivableData)).Deserialize(f);}else data=new ReceivableData();}catch{data=new ReceivableData();}}
 void Save(){using(var f=File.Create(file))new XmlSerializer(typeof(ReceivableData)).Serialize(f,data);}
 List<ReceivableItem> Visible(){IEnumerable<ReceivableItem> q=data.Items;if(!showPaid.Checked)q=q.Where(x=>!x.Achitata);string z=search.Text.Trim();if(z.Length>0)q=q.Where(x=>(x.Client??"").IndexOf(z,StringComparison.CurrentCultureIgnoreCase)>=0);return q.OrderByDescending(x=>x.Rest).ThenBy(x=>x.Client).ToList();}
 void RefreshGrid(){if(grid==null)return;grid.Rows.Clear();foreach(var x in Visible()){int r=grid.Rows.Add(x.Client,x.Factura,x.DataFactura.ToString("dd.MM.yyyy"),x.SumaInitiala.ToString("N2"),x.Incasat.ToString("N2"),x.Rest.ToString("N2"),x.DataUltimeiIncasari.HasValue?x.DataUltimeiIncasari.Value.ToString("dd.MM.yyyy"):"",x.Achitata?"INCASATA":"DE INCASAT",x.Observatii);grid.Rows[r].DefaultCellStyle.BackColor=x.Achitata?Color.Honeydew:Color.White;}total.Text="TOTAL DE INCASAT\n"+data.Items.Sum(x=>x.Rest).ToString("N2")+" LEI";received.Text="INCASAT INREGISTRAT\n"+data.Items.Sum(x=>x.Incasat).ToString("N2")+" LEI";count.Text="FACTURI NEINCASATE\n"+data.Items.Count(x=>!x.Achitata);}
 ReceivableItem Selected(){if(grid.SelectedRows.Count==0)return null;string client=Convert.ToString(grid.SelectedRows[0].Cells[0].Value), factura=Convert.ToString(grid.SelectedRows[0].Cells[1].Value);return data.Items.FirstOrDefault(x=>x.Client==client&&x.Factura==factura);}
 void RegisterPayment(){var x=Selected();if(x==null){MessageBox.Show("Selecteaza factura pentru care ai incasat bani.");return;}if(x.Achitata){MessageBox.Show("Factura este deja incasata integral.");return;}using(var f=new ReceiptForm(x.Rest)){if(f.ShowDialog(this)==DialogResult.OK){x.Incasat=Math.Min(x.SumaInitiala,x.Incasat+f.Amount);x.DataUltimeiIncasari=f.PayDate;Save();RefreshGrid();}}}
 void AddManual(){using(var f=new CustomerInvoiceForm()){if(f.ShowDialog(this)==DialogResult.OK){var ex=data.Items.FirstOrDefault(x=>Eq(x.Client,f.Result.Client)&&Eq(x.Factura,f.Result.Factura));if(ex!=null){MessageBox.Show("Factura exista deja pentru acest client.");return;}data.Items.Add(f.Result);Save();RefreshGrid();}}}
 void ImportCsv(){var o=new OpenFileDialog{Filter="CSV / Text (*.csv;*.txt)|*.csv;*.txt|Toate fisierele|*.*"};if(o.ShowDialog()!=DialogResult.OK)return;int add=0,upd=0;try{foreach(var raw in File.ReadAllLines(o.FileName,System.Text.Encoding.Default)){if(string.IsNullOrWhiteSpace(raw))continue;char sep=raw.Count(c=>c==';')>=raw.Count(c=>c==',')?';':',';var a=raw.Split(sep);if(a.Length<4)continue;string client=a[0].Trim().Trim('"'),fact=a[1].Trim().Trim('"');DateTime dt;decimal sum;if(client.ToUpperInvariant().Contains("CLIENT")&&fact.ToUpperInvariant().Contains("FACT"))continue;if(!DateTime.TryParse(a[2].Trim().Trim('"'),new CultureInfo("ro-RO"),DateTimeStyles.None,out dt))dt=DateTime.Today;if(!decimal.TryParse(a[3].Trim().Trim('"'),NumberStyles.Any,new CultureInfo("ro-RO"),out sum)&&!decimal.TryParse(a[3].Trim().Trim('"').Replace(",","."),NumberStyles.Any,CultureInfo.InvariantCulture,out sum))continue;var ex=data.Items.FirstOrDefault(x=>Eq(x.Client,client)&&Eq(x.Factura,fact));if(ex==null){data.Items.Add(new ReceivableItem{Client=client,Factura=fact,DataFactura=dt,SumaInitiala=sum});add++;}else{ex.SumaInitiala=sum;ex.DataFactura=dt;upd++;}}Save();RefreshGrid();MessageBox.Show("Import finalizat. Adaugate: "+add+" | Actualizate: "+upd+".\nIncasarile introduse manual au fost pastrate.");}catch(Exception ex){MessageBox.Show("Import nereusit: "+ex.Message);}}
 void ExportCsv(){var s=new SaveFileDialog{Filter="CSV|*.csv",FileName="Clienti_de_incasat.csv"};if(s.ShowDialog()!=DialogResult.OK)return;using(var w=new StreamWriter(s.FileName,false,System.Text.Encoding.UTF8)){w.WriteLine("Client;Factura;Data factura;Suma initiala;Incasat;Rest;Ultima incasare;Status");foreach(var x in data.Items)w.WriteLine(string.Join(";",new[]{Q(x.Client),Q(x.Factura),x.DataFactura.ToString("dd.MM.yyyy"),x.SumaInitiala.ToString(CultureInfo.InvariantCulture),x.Incasat.ToString(CultureInfo.InvariantCulture),x.Rest.ToString(CultureInfo.InvariantCulture),x.DataUltimeiIncasari.HasValue?x.DataUltimeiIncasari.Value.ToString("dd.MM.yyyy"):"",x.Achitata?"INCASATA":"DE INCASAT"}));}}
 static bool Eq(string a,string b){return string.Equals((a??"").Trim(),(b??"").Trim(),StringComparison.CurrentCultureIgnoreCase);}static string Q(string s){return "\""+(s??"").Replace("\"","\"\"")+"\"";}
}
public class ReceiptForm:Form{public decimal Amount;public DateTime PayDate;TextBox amount;DateTimePicker date;public ReceiptForm(decimal rest){Text="Inregistreaza incasare";Width=390;Height=210;StartPosition=FormStartPosition.CenterParent;Controls.Add(new Label{Text="Suma incasata (rest "+rest.ToString("N2")+" LEI)",Left=20,Top=20,Width=320});amount=new TextBox{Left=20,Top=45,Width=330,Text=rest.ToString("0.00")};Controls.Add(amount);Controls.Add(new Label{Text="Data incasarii",Left=20,Top=80,Width=120});date=new DateTimePicker{Left=145,Top=76,Width=205,Format=DateTimePickerFormat.Custom,CustomFormat="dd.MM.yyyy"};Controls.Add(date);var b=new Button{Text="SALVEAZA INCASAREA",Left=170,Top=118,Width=180,Height=34};b.Click+=(s,e)=>{decimal v;if(!decimal.TryParse(amount.Text.Replace(" ","").Replace(",","."),NumberStyles.Any,CultureInfo.InvariantCulture,out v)||v<=0||v>rest+0.005m){MessageBox.Show("Introdu o suma intre 0 si "+rest.ToString("N2")+" LEI.");return;}Amount=v;PayDate=date.Value.Date;DialogResult=DialogResult.OK;Close();};Controls.Add(b);}}
public class CustomerInvoiceForm:Form{public ReceivableItem Result;TextBox client,fact,sum,obs;DateTimePicker date;public CustomerInvoiceForm(){Text="Factura client";Width=480;Height=310;StartPosition=FormStartPosition.CenterParent;int y=20;Controls.Add(new Label{Text="Client",Left=20,Top=y,Width=120});client=new TextBox{Left=150,Top=y-3,Width=280};Controls.Add(client);y+=42;Controls.Add(new Label{Text="Factura",Left=20,Top=y,Width=120});fact=new TextBox{Left=150,Top=y-3,Width=280};Controls.Add(fact);y+=42;Controls.Add(new Label{Text="Data factura",Left=20,Top=y,Width=120});date=new DateTimePicker{Left=150,Top=y-3,Width=280,Format=DateTimePickerFormat.Custom,CustomFormat="dd.MM.yyyy"};Controls.Add(date);y+=42;Controls.Add(new Label{Text="Suma LEI",Left=20,Top=y,Width=120});sum=new TextBox{Left=150,Top=y-3,Width=280};Controls.Add(sum);y+=42;Controls.Add(new Label{Text="Observatii",Left=20,Top=y,Width=120});obs=new TextBox{Left=150,Top=y-3,Width=280};Controls.Add(obs);var b=new Button{Text="SALVEAZA",Left=300,Top=230,Width=130,Height=32};b.Click+=(s,e)=>{decimal v;if(string.IsNullOrWhiteSpace(client.Text)||string.IsNullOrWhiteSpace(fact.Text)||!decimal.TryParse(sum.Text.Replace(" ","").Replace(",","."),NumberStyles.Any,CultureInfo.InvariantCulture,out v)||v<=0){MessageBox.Show("Completeaza clientul, factura si suma.");return;}Result=new ReceivableItem{Client=client.Text.Trim(),Factura=fact.Text.Trim(),DataFactura=date.Value.Date,SumaInitiala=v,Observatii=obs.Text.Trim()};DialogResult=DialogResult.OK;Close();};Controls.Add(b);}}

public class DashboardChart:Panel{
 public string Title="";public int ChartKind=0;public double[] Values=new double[0];public string[] Labels=new string[0];
 public DashboardChart(){DoubleBuffered=true;BackColor=Color.White;Padding=new Padding(8);BorderStyle=BorderStyle.FixedSingle;}
 protected override void OnPaint(PaintEventArgs e){base.OnPaint(e);var g=e.Graphics;g.SmoothingMode=System.Drawing.Drawing2D.SmoothingMode.AntiAlias;using(var f=new Font("Segoe UI",9F,FontStyle.Bold))g.DrawString(Title,f,new SolidBrush(Color.FromArgb(39,58,72)),10,8);var r=new Rectangle(12,34,Math.Max(10,Width-24),Math.Max(10,Height-48));if(Values==null||Values.Length==0||Values.All(v=>v<=0)){using(var f=new Font("Segoe UI",9F))g.DrawString("Nu exista date pentru filtrul selectat.",f,Brushes.Gray,16,70);return;}if(ChartKind==1)PaintDonut(g,r);else PaintBars(g,r,ChartKind==2);}
 void PaintBars(Graphics g,Rectangle r,bool horizontal){double max=Math.Max(1,Values.Max());if(horizontal){int n=Math.Max(1,Values.Length),h=Math.Max(14,(r.Height-8)/n-5);for(int i=0;i<Values.Length;i++){int y=r.Top+i*(h+5);int w=(int)((r.Width-125)*Values[i]/max);using(var b=new SolidBrush(Color.FromArgb(30+i*15,112+i*8,166)))g.FillRectangle(b,r.Left+115,y,w,h);using(var f=new Font("Segoe UI",7.5F)){g.DrawString(i<Labels.Length?Labels[i]:"",f,Brushes.DimGray,r.Left,y+1);g.DrawString(Values[i].ToString("N0"),f,Brushes.DimGray,r.Left+118+w,y+1);}}}else{int n=Math.Max(1,Values.Length),bw=Math.Max(5,(r.Width-10)/n-5);for(int i=0;i<Values.Length;i++){int h=(int)((r.Height-28)*Values[i]/max);int x=r.Left+5+i*(bw+5),y=r.Bottom-20-h;using(var b=new SolidBrush(Color.FromArgb(24,116,170)))g.FillRectangle(b,x,y,bw,h);using(var f=new Font("Segoe UI",6.7F))g.DrawString(i<Labels.Length?Labels[i]:"",f,Brushes.DimGray,x,r.Bottom-18);}}}
 void PaintDonut(Graphics g,Rectangle r){double sum=Values.Sum();if(sum<=0)return;int size=Math.Min(r.Height-5,r.Width-95);var pie=new Rectangle(r.Left+4,r.Top+2,size,size);Color[] cs={Color.FromArgb(42,150,104),Color.FromArgb(202,62,72),Color.FromArgb(35,126,181)};float a=-90;for(int i=0;i<Values.Length;i++){float sw=(float)(360*Values[i]/sum);using(var b=new SolidBrush(cs[i%cs.Length]))g.FillPie(b,pie,a,sw);a+=sw;}int inner=(int)(size*.52);g.FillEllipse(Brushes.White,pie.Left+(size-inner)/2,pie.Top+(size-inner)/2,inner,inner);using(var f=new Font("Segoe UI",8F,FontStyle.Bold))for(int i=0;i<Values.Length;i++){using(var b=new SolidBrush(cs[i%cs.Length]))g.FillRectangle(b,pie.Right+10,pie.Top+8+i*25,10,10);g.DrawString((i<Labels.Length?Labels[i]:"")+" "+Values[i].ToString("N0"),f,Brushes.DimGray,pie.Right+24,pie.Top+4+i*25);}}
}

public class InvoiceForm:Form{public Invoice Result;TextBox nr,tr,co,fa,lei,eur,iban,obs,zile;DateTimePicker prim,scad;int year;public InvoiceForm(Invoice x,int y,int nextNr){year=y;Text=x==null?"OTL • Factura noua":"OTL • Modifica factura";Width=560;Height=610;StartPosition=FormStartPosition.CenterParent;BackColor=Color.FromArgb(239,244,248);Font=new Font("Segoe UI",9.5F);var p=new TableLayoutPanel{Dock=DockStyle.Fill,ColumnCount=2,Padding=new Padding(12),AutoScroll=true};p.ColumnStyles.Add(new ColumnStyle(SizeType.Absolute,170));p.ColumnStyles.Add(new ColumnStyle(SizeType.Percent,100));Controls.Add(p);nr=Add(p,"NR. CRT.");nr.Text=nextNr.ToString();tr=Add(p,"Transportator");co=Add(p,"Comanda");fa=Add(p,"Factura / Data");lei=Add(p,"Total factura LEI");eur=Add(p,"Total EUR");iban=Add(p,"IBAN");prim=AddDate(p,"Data primirii");zile=Add(p,"Scadenta (zile)");zile.Text="30";scad=AddDate(p,"Data scadenta");obs=Add(p,"Observatii");prim.ValueChanged+=(s,e)=>Calc();zile.TextChanged+=(s,e)=>Calc();var b=new Button{Text="SALVEAZA FACTURA",Dock=DockStyle.Fill,Height=38,BackColor=Color.FromArgb(18,112,166),ForeColor=Color.White,Font=new Font("Segoe UI",9F,FontStyle.Bold),FlatStyle=FlatStyle.Standard,UseVisualStyleBackColor=false};b.Click+=(s,e)=>Save();p.Controls.Add(new Label());p.Controls.Add(b);if(x!=null){nr.Text=x.NrCrt.ToString();tr.Text=x.Transportator;co.Text=x.Comanda;fa.Text=x.Factura;lei.Text=x.TotalLei.ToString();eur.Text=x.TotalEur.ToString();iban.Text=x.Iban;prim.Value=x.DataPrimire;zile.Text=x.ZileScadenta.ToString();scad.Value=x.Scadenta;obs.Text=x.Observatii;Result=x;}}
 TextBox Add(TableLayoutPanel p,string l){p.RowCount++;p.RowStyles.Add(new RowStyle(SizeType.Absolute,38));p.Controls.Add(new Label{Text=l,AutoSize=true,Padding=new Padding(0,8,0,0)});var t=new TextBox{Dock=DockStyle.Fill};p.Controls.Add(t);return t;}DateTimePicker AddDate(TableLayoutPanel p,string l){p.RowCount++;p.RowStyles.Add(new RowStyle(SizeType.Absolute,38));p.Controls.Add(new Label{Text=l,AutoSize=true,Padding=new Padding(0,8,0,0)});var d=new DateTimePicker{Format=DateTimePickerFormat.Custom,CustomFormat="dd.MM.yyyy",Dock=DockStyle.Fill};p.Controls.Add(d);return d;}void Calc(){int z;if(int.TryParse(zile.Text,out z))scad.Value=prim.Value.Date.AddDays(z);}decimal Dec(string s){decimal v;decimal.TryParse((s??"").Replace(" ","").Replace(",","."),NumberStyles.Any,CultureInfo.InvariantCulture,out v);return v;}void Save(){int z;if(!int.TryParse(zile.Text,out z))z=0;int nrc;if(!int.TryParse(nr.Text,out nrc)||nrc<=0){MessageBox.Show("NR. CRT. trebuie sa fie un numar mai mare ca 0.");return;}Result=new Invoice{Year=year,NrCrt=nrc,Transportator=tr.Text.Trim(),Comanda=co.Text.Trim(),Factura=fa.Text.Trim(),TotalLei=Dec(lei.Text),TotalEur=Dec(eur.Text),Iban=iban.Text.Trim(),DataPrimire=prim.Value.Date,ZileScadenta=z,Scadenta=scad.Value.Date,ScadentaText=scad.Value.Date.ToString("dd.MM.yyyy"),ScadentaInvalida=false,Observatii=obs.Text.Trim(),DataPlatii=Result==null?null:Result.DataPlatii};DialogResult=DialogResult.OK;Close();}}
public class DateDialog:Form{DateTimePicker d;public DateTime Value{get{return d.Value.Date;}}public DateDialog(string title,DateTime val){Text=title;Width=300;Height=140;StartPosition=FormStartPosition.CenterParent;d=new DateTimePicker{Format=DateTimePickerFormat.Custom,CustomFormat="dd.MM.yyyy",Value=val,Left=20,Top=15,Width=240};var b=new Button{Text="OK",Left=170,Top=52,Width=90};b.Click+=(s,e)=>{DialogResult=DialogResult.OK;Close();};Controls.Add(d);Controls.Add(b);}}

public static class XlsxReader{
 public static List<Invoice> Read(string path){var all=new List<Invoice>();using(var z=ZipFile.OpenRead(path)){var shared=ReadShared(z);var wb=XDocument.Load(z.GetEntry("xl/workbook.xml").Open());XNamespace ns="http://schemas.openxmlformats.org/spreadsheetml/2006/main";XNamespace rel="http://schemas.openxmlformats.org/officeDocument/2006/relationships";var rels=XDocument.Load(z.GetEntry("xl/_rels/workbook.xml.rels").Open());XNamespace rns="http://schemas.openxmlformats.org/package/2006/relationships";foreach(var sh in wb.Descendants(ns+"sheet")){int year;if(!int.TryParse((string)sh.Attribute("name"),out year))continue;string rid=(string)sh.Attribute(rel+"id");var rr=rels.Descendants(rns+"Relationship").FirstOrDefault(x=>(string)x.Attribute("Id")==rid);if(rr==null)continue;string target=(string)rr.Attribute("Target");if(target.StartsWith("/"))target=target.TrimStart('/');else target="xl/"+target.Replace("../","");var en=z.GetEntry(target);if(en==null)continue;all.AddRange(ReadSheet(en,shared,year));}}return all;}
 static List<string> ReadShared(ZipArchive z){var l=new List<string>();var e=z.GetEntry("xl/sharedStrings.xml");if(e==null)return l;var d=XDocument.Load(e.Open());XNamespace n="http://schemas.openxmlformats.org/spreadsheetml/2006/main";foreach(var si in d.Descendants(n+"si"))l.Add(string.Concat(si.Descendants(n+"t").Select(x=>x.Value)));return l;}
 static List<Invoice> ReadSheet(ZipArchiveEntry e,List<string> ss,int year){var outp=new List<Invoice>();var d=XDocument.Load(e.Open());XNamespace n="http://schemas.openxmlformats.org/spreadsheetml/2006/main";var rows=d.Descendants(n+"row").ToList();if(rows.Count<2)return outp;Dictionary<int,string> headers=null;foreach(var row in rows){var vals=Cells(row,n,ss);if(headers==null){headers=vals.ToDictionary(k=>k.Key,k=>(k.Value??"").Trim().ToUpperInvariant());if(!headers.Values.Any(x=>x.Contains("TRANSPORT"))){headers=null;continue;}continue;}string tr=By(vals,headers,"TRANSPORT"), fact=By(vals,headers,"FACTUR");if(string.IsNullOrWhiteSpace(tr)&&string.IsNullOrWhiteSpace(fact))continue; int nr=outp.Count+1; // NR. CRT. urmeaza ordinea fizica a randurilor din Excel.
DateTime prim=Date(By(vals,headers,"PR.PLICULUI","PRIMIR")); string scRaw=ByExact(vals,headers,"SCADENTA"); DateTime sc=Date(scRaw); bool scInvalid=!string.IsNullOrWhiteSpace(scRaw)&&sc.Year<2000; if(string.IsNullOrWhiteSpace(scRaw)){scRaw=By(vals,headers,"SCADENTA RECALCULATA");sc=Date(scRaw);scInvalid=!string.IsNullOrWhiteSpace(scRaw)&&sc.Year<2000;} if(string.IsNullOrWhiteSpace(scRaw)&&prim.Year>2000){sc=prim.AddDays(30);scRaw=sc.ToString("dd.MM.yyyy");scInvalid=false;} var inv=new Invoice{Year=year,NrCrt=nr,Transportator=tr,Comanda=By(vals,headers,"COMAND"),Factura=fact,TotalLei=Num(By(vals,headers,"TOTAL FACT/LEI","TOTAL FACTURA LEI","TOTAL LEI","TOTAL/LEI")),TotalEur=Num(By(vals,headers,"TOTAL/ EURO","TOTAL/EURO","TOTAL EUR","TOTAL EURO")),Iban=By(vals,headers,"IBAN"),DataPrimire=prim.Year>2000?prim:DateTime.Today,Scadenta=sc.Year>2000?sc:DateTime.MinValue,ScadentaText=NormalizeDateText(scRaw,sc),ScadentaInvalida=scInvalid,Observatii=By(vals,headers,"OBSERV")};var pay=Date(By(vals,headers,"DATA PLAT"));if(pay.Year>2000)inv.DataPlatii=pay;inv.ZileScadenta=inv.ScadentaInvalida?0:(inv.Scadenta-inv.DataPrimire).Days;outp.Add(inv);}return outp;}
 static Dictionary<int,string> Cells(XElement row,XNamespace n,List<string> ss){var m=new Dictionary<int,string>();foreach(var c in row.Elements(n+"c")){string r=(string)c.Attribute("r")??"A1";int col=Col(r);string t=(string)c.Attribute("t");string v=(string)c.Element(n+"v")??"";if(t=="s"){int i;if(int.TryParse(v,out i)&&i>=0&&i<ss.Count)v=ss[i];}else if(t=="inlineStr")v=string.Concat(c.Descendants(n+"t").Select(x=>x.Value));m[col]=v;}return m;}static int Col(string r){int x=0;foreach(char c in r){if(!char.IsLetter(c))break;x=x*26+(char.ToUpperInvariant(c)-'A'+1);}return x;}static string ByExact(Dictionary<int,string> v,Dictionary<int,string> h,string key){var q=h.FirstOrDefault(x=>x.Value==key);return q.Value!=null&&v.ContainsKey(q.Key)?v[q.Key]:"";}static string By(Dictionary<int,string> v,Dictionary<int,string> h,params string[] keys){foreach(var k in keys){var q=h.FirstOrDefault(x=>x.Value.Contains(k));if(q.Value!=null&&v.ContainsKey(q.Key))return v[q.Key];}return "";}static int IntNum(string s){int x;if(int.TryParse((s??"").Trim(),out x))return x;double d;if(double.TryParse((s??"").Trim(),NumberStyles.Any,CultureInfo.InvariantCulture,out d))return (int)d;return 0;}static decimal Num(string s){decimal x;decimal.TryParse((s??"").Replace(" ","").Replace(",","."),NumberStyles.Any,CultureInfo.InvariantCulture,out x);return x;}static string NormalizeDateText(string raw,DateTime parsed){if(string.IsNullOrWhiteSpace(raw))return ""; double o;if(double.TryParse(raw,NumberStyles.Any,CultureInfo.InvariantCulture,out o)&&o>20000&&o<80000&&parsed.Year>2000)return parsed.ToString("dd.MM.yyyy");return raw.Trim();}static DateTime Date(string s){double o;if(double.TryParse(s,NumberStyles.Any,CultureInfo.InvariantCulture,out o)&&o>20000&&o<80000)return DateTime.FromOADate(o);DateTime d;string[] f={"dd.MM.yyyy","d.M.yyyy","dd/MM/yyyy","d/M/yyyy","yyyy-MM-dd"};return DateTime.TryParseExact(s,f,CultureInfo.InvariantCulture,DateTimeStyles.None,out d)?d:DateTime.MinValue;}
}
static class Program{[STAThread]static void Main(){
 try{
  Application.EnableVisualStyles(); Application.SetCompatibleTextRenderingDefault(false); Application.Run(new MainForm());
 }catch(Exception ex){
  try{string dir=Path.Combine(Environment.GetFolderPath(Environment.SpecialFolder.MyDocuments),"ScadentarTransportatori");Directory.CreateDirectory(dir);File.WriteAllText(Path.Combine(dir,"eroare.log"),DateTime.Now.ToString("s")+Environment.NewLine+ex.ToString());}catch{}
  MessageBox.Show("Aplicatia nu a putut porni. Detaliile au fost salvate in Documents\\ScadentarTransportatori\\eroare.log\n\n"+ex.Message,"Scadentar Transportatori - Eroare",MessageBoxButtons.OK,MessageBoxIcon.Error);
 }
}}
}
